name: Build and Deploy to DockerHub
run-name: ${{github.actor}} initiated the Deploy workflow
on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
            name: spring-boot-jar
      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: chetanchandane/spring-boot-rest-api-todo
          tags: latest,${{ github.sha }}
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

