name: Test and Deploy to DockerHub
run-name: ${{ github.actor }} initiated this workflow
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run unit tests on Java 23
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Clear project
        run: mvn clean

      - name: Compile project
        run: mvn compile

      - name: Run test cases
        run: mvn test

      - name: Build with Maven
        run: mvn clean install package

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: spring-boot-jar
          path: target/spring-boot-rest-api-todo.jar

  deploy:
    runs-on: ubuntu-latest
    name: Build and Push Docker Image
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: spring-boot-jar

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: chetanchandane/spring-boot-rest-api-todo
          tags: latest,${{ github.sha }}
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
