name: Run test on Java 11
run-name: ${{ github.actor }} has initiated this test workflow.
on:
  push:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run unit tests on Java 23
    steps:
      - name: check out branch
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: clear project
        run: mvn clean

      - name: compile project
        run: mvn compile

      - name: run test cases
        run: mvn test

      - name: build with Maven
        run: mvn clean install package




